### ISSUE TITLE
v1.0 Checklist

### ISSUE THREAD

**Issue by edmundhung** [edmundhung/conform#1]
# Checklist

- [x] Conform Playground (#3)
- [x] Improved controlled component support (e.g. `material-ui` select) (#19)
- [x] Better test coverage
- [x] Simplify example setup (#23)
- [x] Documentation website (#29)
- [ ] Testing guide (a.k.a. How to test)
- [x] Button value validation (#21)
- [x] Better Boolean support (#5)
- [x] [Yup](https://github.com/jquense/yup) support (#15)
- [x] Examples with [create-react-app](https://github.com/facebook/create-react-app)
- [ ] Example with [next.js](https://github.com/vercel/next.js)
- [ ] Setting up [changeset](https://github.com/changesets/changesets) (#2)
- [x] Autofoucs on error (JS+No-JS) (#33)
- [x] File upload support (#72)
- [x] Improve array support (#71)
- [ ] Allows combining list commands
- [x] Async validation (#40)

**Comment by dev-xo** [comment]
Amazing work mate!
Would love to see that `Testing guide (a.k.a. How to test)` task completed!
